// Auto-generated by scripts/gen-images.cjs. Do not edit by hand —
// run `npm run gen-images` after syncing the bundle.
//
// React Native's Metro bundler resolves `require()` of static assets at
// build time only. We map slug-variant -> module ID so other code can do
// `getImage('arnold-press', 'peak')` without dynamic require.

export const IMAGES: Record<string, number> = {
  'arnold-press-peak': require('../assets/images/flat/arnold-press-peak.webp'),
  'arnold-press-start': require('../assets/images/flat/arnold-press-start.webp'),
  'banded-lateral-walk-peak': require('../assets/images/flat/banded-lateral-walk-peak.webp'),
  'banded-lateral-walk-start': require('../assets/images/flat/banded-lateral-walk-start.webp'),
  'barbell-glute-bridge-peak': require('../assets/images/flat/barbell-glute-bridge-peak.webp'),
  'barbell-glute-bridge-start': require('../assets/images/flat/barbell-glute-bridge-start.webp'),
  'behind-the-back-barbell-shrug-peak': require('../assets/images/flat/behind-the-back-barbell-shrug-peak.webp'),
  'behind-the-back-barbell-shrug-start': require('../assets/images/flat/behind-the-back-barbell-shrug-start.webp'),
  'behind-the-neck-press-peak': require('../assets/images/flat/behind-the-neck-press-peak.webp'),
  'behind-the-neck-press-start': require('../assets/images/flat/behind-the-neck-press-start.webp'),
  'bench-dips-peak': require('../assets/images/flat/bench-dips-peak.webp'),
  'bench-dips-start': require('../assets/images/flat/bench-dips-start.webp'),
  'bent-arm-ez-bar-pullover-peak': require('../assets/images/flat/bent-arm-ez-bar-pullover-peak.webp'),
  'bent-arm-ez-bar-pullover-start': require('../assets/images/flat/bent-arm-ez-bar-pullover-start.webp'),
  'bulgarian-split-squat-peak': require('../assets/images/flat/bulgarian-split-squat-peak.webp'),
  'bulgarian-split-squat-start': require('../assets/images/flat/bulgarian-split-squat-start.webp'),
  'cable-crunch-peak': require('../assets/images/flat/cable-crunch-peak.webp'),
  'cable-crunch-start': require('../assets/images/flat/cable-crunch-start.webp'),
  'cable-external-rotation-peak': require('../assets/images/flat/cable-external-rotation-peak.webp'),
  'cable-external-rotation-start': require('../assets/images/flat/cable-external-rotation-start.webp'),
  'double-kettlebell-row-peak': require('../assets/images/flat/double-kettlebell-row-peak.webp'),
  'double-kettlebell-row-start': require('../assets/images/flat/double-kettlebell-row-start.webp'),
  'dumbbell-calf-raise-peak': require('../assets/images/flat/dumbbell-calf-raise-peak.webp'),
  'dumbbell-calf-raise-start': require('../assets/images/flat/dumbbell-calf-raise-start.webp'),
  'ez-bar-overhead-extension-peak': require('../assets/images/flat/ez-bar-overhead-extension-peak.webp'),
  'ez-bar-overhead-extension-start': require('../assets/images/flat/ez-bar-overhead-extension-start.webp'),
  'floor-kettlebell-pullover-peak': require('../assets/images/flat/floor-kettlebell-pullover-peak.webp'),
  'floor-kettlebell-pullover-start': require('../assets/images/flat/floor-kettlebell-pullover-start.webp'),
  'kettlebell-deadlift-peak': require('../assets/images/flat/kettlebell-deadlift-peak.webp'),
  'kettlebell-deadlift-start': require('../assets/images/flat/kettlebell-deadlift-start.webp'),
  'one-arm-kettlebell-row-peak': require('../assets/images/flat/one-arm-kettlebell-row-peak.webp'),
  'one-arm-kettlebell-row-start': require('../assets/images/flat/one-arm-kettlebell-row-start.webp'),
  'pec-deck-peak': require('../assets/images/flat/pec-deck-peak.webp'),
  'pec-deck-start': require('../assets/images/flat/pec-deck-start.webp'),
  'push-press-peak': require('../assets/images/flat/push-press-peak.webp'),
  'push-press-start': require('../assets/images/flat/push-press-start.webp'),
  'smith-machine-bent-over-row-peak': require('../assets/images/flat/smith-machine-bent-over-row-peak.webp'),
  'smith-machine-bent-over-row-start': require('../assets/images/flat/smith-machine-bent-over-row-start.webp'),
  'smith-machine-squat-peak': require('../assets/images/flat/smith-machine-squat-peak.webp'),
  'smith-machine-squat-start': require('../assets/images/flat/smith-machine-squat-start.webp'),
  'wide-grip-seated-cable-row-peak': require('../assets/images/flat/wide-grip-seated-cable-row-peak.webp'),
  'wide-grip-seated-cable-row-start': require('../assets/images/flat/wide-grip-seated-cable-row-start.webp'),
};

// slug -> animated WebP loop module ID. Play with expo-image (stock RN
// <Image> does not animate WebP); a slug is absent when it has no animation.
export const ANIMATIONS: Record<string, number> = {
  'arnold-press': require('../assets/images/animations/arnold-press.webp'),
  'banded-lateral-walk': require('../assets/images/animations/banded-lateral-walk.webp'),
  'barbell-glute-bridge': require('../assets/images/animations/barbell-glute-bridge.webp'),
  'behind-the-back-barbell-shrug': require('../assets/images/animations/behind-the-back-barbell-shrug.webp'),
  'behind-the-neck-press': require('../assets/images/animations/behind-the-neck-press.webp'),
  'bench-dips': require('../assets/images/animations/bench-dips.webp'),
  'bent-arm-ez-bar-pullover': require('../assets/images/animations/bent-arm-ez-bar-pullover.webp'),
  'bulgarian-split-squat': require('../assets/images/animations/bulgarian-split-squat.webp'),
  'cable-crunch': require('../assets/images/animations/cable-crunch.webp'),
  'cable-external-rotation': require('../assets/images/animations/cable-external-rotation.webp'),
  'double-kettlebell-row': require('../assets/images/animations/double-kettlebell-row.webp'),
  'dumbbell-calf-raise': require('../assets/images/animations/dumbbell-calf-raise.webp'),
  'ez-bar-overhead-extension': require('../assets/images/animations/ez-bar-overhead-extension.webp'),
  'floor-kettlebell-pullover': require('../assets/images/animations/floor-kettlebell-pullover.webp'),
  'kettlebell-deadlift': require('../assets/images/animations/kettlebell-deadlift.webp'),
  'one-arm-kettlebell-row': require('../assets/images/animations/one-arm-kettlebell-row.webp'),
  'pec-deck': require('../assets/images/animations/pec-deck.webp'),
  'push-press': require('../assets/images/animations/push-press.webp'),
  'smith-machine-bent-over-row': require('../assets/images/animations/smith-machine-bent-over-row.webp'),
  'smith-machine-squat': require('../assets/images/animations/smith-machine-squat.webp'),
  'wide-grip-seated-cable-row': require('../assets/images/animations/wide-grip-seated-cable-row.webp'),
};

export type ImageVariant = 'start' | 'peak';

export function getImage(slug: string, variant: ImageVariant): number | undefined {
  return IMAGES[`${slug}-${variant}`];
}

export function getAnimation(slug: string): number | undefined {
  return ANIMATIONS[slug];
}
