// Regenerate lib/images.ts from assets/images/{flat,classic,animations,muscles,equipment}.
// React Native bundles static assets at build time, so each image needs an
// explicit `require()` call. After syncing the preview bundle, run:
//
//   npm run gen-images
//
// Commit the resulting lib/images.ts.

const { readdirSync, writeFileSync, existsSync } = require('node:fs');
const { join } = require('node:path');

const ROOT = join(__dirname, '..');
const OUT = join(ROOT, 'lib/images.ts');

const webps = (dir) =>
  existsSync(join(ROOT, dir))
    ? readdirSync(join(ROOT, dir)).filter((f) => f.endsWith('.webp')).sort()
    : [];

// Build a `'key': require('<dir>/<file>'),` block. `key` is the filename
// without the .webp extension (slug-variant for stills, slug for animations,
// icon basename for muscles/equipment).
const block = (dir) =>
  webps(dir)
    .map((f) => `  '${f.replace(/\.webp$/, '')}': require('../${dir}/${f}'),`)
    .join('\n');

const flat = webps('assets/images/flat');
const classic = webps('assets/images/classic');
const anim = webps('assets/images/animations');
const muscles = webps('assets/images/muscles');
const equipment = webps('assets/images/equipment');

const out = `// Auto-generated by scripts/gen-images.cjs. Do not edit by hand —
// run \`npm run gen-images\` after syncing the bundle.
//
// React Native's Metro bundler resolves \`require()\` of static assets at
// build time only. We map a string key -> module ID so other code can resolve
// assets without a dynamic require.

export type ImageVariant = 'start' | 'peak';
export type ImageStyle = 'flat' | 'classic';

// slug-variant -> module ID, white-background flat stills.
export const IMAGES: Record<string, number> = {
${block('assets/images/flat')}
};

// slug-variant -> module ID, transparent matte-clay classic stills.
export const CLASSIC: Record<string, number> = {
${block('assets/images/classic')}
};

// slug -> animated WebP loop module ID. Play with expo-image (stock RN
// <Image> does not animate WebP); a slug is absent when it has no animation.
export const ANIMATIONS: Record<string, number> = {
${block('assets/images/animations')}
};

// icon basename (e.g. 'anterior-deltoid') -> module ID.
export const MUSCLE_ICONS: Record<string, number> = {
${block('assets/images/muscles')}
};

export const EQUIPMENT_ICONS: Record<string, number> = {
${block('assets/images/equipment')}
};

export function getImage(
  slug: string,
  variant: ImageVariant,
  style: ImageStyle = 'flat',
): number | undefined {
  const map = style === 'classic' ? CLASSIC : IMAGES;
  return map[\`\${slug}-\${variant}\`];
}

export function getAnimation(slug: string): number | undefined {
  return ANIMATIONS[slug];
}

// \`file\` is the taxonomy \`image\` value, e.g. 'anterior-deltoid.webp'.
export function getMuscleIcon(file: string | undefined): number | undefined {
  return file ? MUSCLE_ICONS[file.replace(/\.webp$/, '')] : undefined;
}

export function getEquipmentIcon(file: string | undefined): number | undefined {
  return file ? EQUIPMENT_ICONS[file.replace(/\.webp$/, '')] : undefined;
}
`;

writeFileSync(OUT, out);
console.log(
  `Generated ${flat.length} flat + ${classic.length} classic + ${anim.length} anim + ` +
    `${muscles.length} muscle + ${equipment.length} equipment -> lib/images.ts`,
);
