// Regenerate lib/images.ts from assets/images/{flat,animations}/*.webp.
// React Native bundles static assets at build time, so each image needs an
// explicit `require()` call. After syncing the preview bundle, run:
//
//   npm run gen-images
//
// Commit the resulting lib/images.ts.

const { readdirSync, writeFileSync, existsSync } = require('node:fs');
const { join } = require('node:path');

const ROOT = join(__dirname, '..');
const FLAT_DIR = join(ROOT, 'assets/images/flat');
const ANIM_DIR = join(ROOT, 'assets/images/animations');
const OUT = join(ROOT, 'lib/images.ts');

const webps = (dir) =>
  existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith('.webp')).sort() : [];

const flat = webps(FLAT_DIR);
const anim = webps(ANIM_DIR);

const flatLines = flat.map((f) => {
  const key = f.replace(/\.webp$/, '');
  return `  '${key}': require('../assets/images/flat/${f}'),`;
});

const animLines = anim.map((f) => {
  const key = f.replace(/\.webp$/, '');
  return `  '${key}': require('../assets/images/animations/${f}'),`;
});

const out = `// Auto-generated by scripts/gen-images.cjs. Do not edit by hand —
// run \`npm run gen-images\` after syncing the bundle.
//
// React Native's Metro bundler resolves \`require()\` of static assets at
// build time only. We map slug-variant -> module ID so other code can do
// \`getImage('arnold-press', 'peak')\` without dynamic require.

export const IMAGES: Record<string, number> = {
${flatLines.join('\n')}
};

// slug -> animated WebP loop module ID. Play with expo-image (stock RN
// <Image> does not animate WebP); a slug is absent when it has no animation.
export const ANIMATIONS: Record<string, number> = {
${animLines.join('\n')}
};

export type ImageVariant = 'start' | 'peak';

export function getImage(slug: string, variant: ImageVariant): number | undefined {
  return IMAGES[\`\${slug}-\${variant}\`];
}

export function getAnimation(slug: string): number | undefined {
  return ANIMATIONS[slug];
}
`;

writeFileSync(OUT, out);
console.log(`Generated ${flat.length} stills + ${anim.length} animations -> lib/images.ts`);
