// Regenerate lib/images.ts from assets/images/{flat,samples,muscles,equipment}.
// React Native bundles static assets at build time, so each image needs an
// explicit `require()` call. After syncing the free bundle, run:
//
//   npm run gen-images
//
// Commit the resulting lib/images.ts.

const { readdirSync, writeFileSync, existsSync } = require('node:fs');
const { join } = require('node:path');

const ROOT = join(__dirname, '..');
const OUT = join(ROOT, 'lib/images.ts');

const webps = (dir) =>
  existsSync(join(ROOT, dir))
    ? readdirSync(join(ROOT, dir)).filter((f) => f.endsWith('.webp')).sort()
    : [];

// Build a `'key': require('<dir>/<file>'),` block. `key` is the filename
// without the .webp extension (slug-variant for flat stills, bare slug for the
// sample animations, icon basename for muscles/equipment).
const block = (dir, files = webps(dir)) =>
  files
    .map((f) => `  '${f.replace(/\.webp$/, '')}': require('../${dir}/${f}'),`)
    .join('\n');

const flat = webps('assets/images/flat');
const samples = webps('assets/images/samples').filter(
  (file) => !/-(start|peak|main)\.webp$/.test(file),
);
const muscles = webps('assets/images/muscles');
const equipment = webps('assets/images/equipment');

const out = `// Auto-generated by scripts/gen-images.cjs. Do not edit by hand —
// run \`npm run gen-images\` after syncing the bundle.
//
// React Native's Metro bundler resolves \`require()\` of static assets at
// build time only. We map a string key -> module ID so other code can resolve
// assets without a dynamic require.

export type ImageVariant = 'start' | 'peak' | 'main';

// slug-variant -> module ID, free-tier flat (white-background) stills. A slug
// ships either a 'start'/'peak' pair or a single 'main' pose.
export const IMAGES: Record<string, number> = {
${block('assets/images/flat')}
};

// slug -> module ID, Standard-tier looping animations (transparent WebP) — the
// exact clips shown on repdb.co. One animation per slug; the paid-tier preview
// gallery is DERIVED from these keys (see SAMPLE_SLUGS).
export const SAMPLES: Record<string, number> = {
${block('assets/images/samples', samples)}
};

// icon basename (e.g. 'anterior-deltoid') -> module ID.
export const MUSCLE_ICONS: Record<string, number> = {
${block('assets/images/muscles')}
};

export const EQUIPMENT_ICONS: Record<string, number> = {
${block('assets/images/equipment')}
};

/** Free-tier flat still. \`slug\` is already alias-resolved by the caller. */
export function getImage(slug: string, variant: ImageVariant): number | undefined {
  return IMAGES[\`\${slug}-\${variant}\`];
}

/** Standard-tier looping animation module ID, or undefined if none ships. */
export function getSampleAnimation(slug: string): number | undefined {
  return SAMPLES[slug];
}

// The sample slugs, straight from the SAMPLES keys — the one source of truth
// for the paid-tier preview gallery. Sorted for a stable render order.
export const SAMPLE_SLUGS: string[] = Object.keys(SAMPLES).sort();

// \`file\` is the taxonomy \`image\` value, e.g. 'anterior-deltoid.webp'.
export function getMuscleIcon(file: string | undefined): number | undefined {
  return file ? MUSCLE_ICONS[file.replace(/\.webp$/, '')] : undefined;
}

export function getEquipmentIcon(file: string | undefined): number | undefined {
  return file ? EQUIPMENT_ICONS[file.replace(/\.webp$/, '')] : undefined;
}
`;

writeFileSync(OUT, out);
console.log(
  `Generated ${flat.length} flat + ${samples.length} sample animation + ` +
    `${muscles.length} muscle + ${equipment.length} equipment -> lib/images.ts`,
);
